language: python

matrix:
  include:
  # Create travis test builds using specific tox environment
  - python: 3.5
    env: TOX_ENV=py35
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.7
    env: TOX_ENV=py37
    dist: xenial

install: 
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls