language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install numpy pytest-cov coveralls"
# command to run tests
script:
  - py.test
after_success:
  - coveralls